import type { ImageSource } from "expo-image";

/**
 * Metro bundles assets only when their paths are statically required.
 * This registry maps the local paths stored in exercises.json to those assets.
 */
type ExerciseImageSource = ImageSource | string | number;

const LOCAL_EXERCISE_IMAGES: Record<string, ExerciseImageSource> = {
  "../../assets/images/workout/1.5-Rep-Bodyweight-Squat.webp": require(
    "../../assets/images/workout/Bodyweight-Squat.webp"
  ),
  "../../assets/images/workout/Alternate-Dumbbell-Front-Raise-Neutral-Grip.webp": require("../../assets/images/workout/Alternate-Dumbbell-Front-Raise-Neutral-Grip.webp"),
  "../../assets/images/workout/Alternating-Dumbbell-Curl.webp": require("../../assets/images/workout/Alternating-Dumbbell-Curl.webp"),
  "../../assets/images/workout/Band-Seated-Hip-Abduction.webp": require("../../assets/images/workout/Band-Seated-Hip-Abduction.webp"),
  "../../assets/images/workout/Banded-Clams.webp": require("../../assets/images/workout/Banded-Clams.webp"),
  "../../assets/images/workout/Banded-Glute-Bridge.webp": require("../../assets/images/workout/Banded-Glute-Bridge.webp"),
  "../../assets/images/workout/Barbell-Bench-Press.webp": require("../../assets/images/workout/Barbell-Bench-Press.webp"),
  "../../assets/images/workout/Barbell-Bent-Over-Rows-Supinated-Grip.webp": require("../../assets/images/workout/Barbell-Bent-Over-Rows-Supinated-Grip.webp"),
  "../../assets/images/workout/Barbell-Bulgarian-Split-Squat.webp": require("../../assets/images/workout/Barbell-Bulgarian-Split-Squat.webp"),
  "../../assets/images/workout/Barbell-Curl.webp": require("../../assets/images/workout/Barbell-Curl.webp"),
  "../../assets/images/workout/Barbell-Deadlift.webp": require("../../assets/images/workout/Barbell-Deadlift.webp"),
  "../../assets/images/workout/Barbell-Declined-Bench-Press.webp": require("../../assets/images/workout/Barbell-Declined-Bench-Press.webp"),
  "../../assets/images/workout/Barbell-Front-Raise.webp": require("../../assets/images/workout/Barbell-Front-Raise.webp"),
  "../../assets/images/workout/Barbell-Hip-Thrust.webp": require("../../assets/images/workout/Barbell-Hip-Thrust.webp"),
  "../../assets/images/workout/Barbell-Pullover.webp": require("../../assets/images/workout/Barbell-Pullover.webp"),
  "../../assets/images/workout/Barbell-Push-Press.webp": require("../../assets/images/workout/Barbell-Push-Press.webp"),
  "../../assets/images/workout/Barbell-Romanian-Deadlift.webp": require("../../assets/images/workout/Barbell-Romanian-Deadlift.webp"),
  "../../assets/images/workout/Barbell-Row.webp": require("../../assets/images/workout/Barbell-Row.webp"),
  "../../assets/images/workout/Barbell-Shrug.webp": require("../../assets/images/workout/Barbell-Shrug.webp"),
  "../../assets/images/workout/Barbell-Sumo-Deadlift.webp": require("../../assets/images/workout/Barbell-Sumo-Deadlift.webp"),
  "../../assets/images/workout/Barbell-Upright-Row.webp": require("../../assets/images/workout/Barbell-Upright-Row.webp"),
  "../../assets/images/workout/Behind-Neck-Pulldown.webp": require("../../assets/images/workout/Behind-Neck-Pulldown.webp"),
  "../../assets/images/workout/Behind-the-Neck-Pull-Up.webp": require("../../assets/images/workout/Behind-the-Neck-Pull-Up.webp"),
  "../../assets/images/workout/Bench-Dips.webp": require("../../assets/images/workout/Bench-Dips.webp"),
  "../../assets/images/workout/Bent-Knee-Reverse-Crunch.webp": require("../../assets/images/workout/Bent-Knee-Reverse-Crunch.webp"),
  "../../assets/images/workout/Bent-Over-Lateral-Raise.webp": require("../../assets/images/workout/Bent-Over-Lateral-Raise.webp"),
  "../../assets/images/workout/Bird-Dog.webp": require("../../assets/images/workout/Bird-Dog.webp"),
  "../../assets/images/workout/Bodyweight-Bulgarian-Split-Squat.webp": require("../../assets/images/workout/Bodyweight-Bulgarian-Split-Squat.webp"),
  "../../assets/images/workout/Bodyweight-Frog-Pump.webp": require("../../assets/images/workout/Bodyweight-Frog-Pump.webp"),
  "../../assets/images/workout/Bodyweight-Glute-Bridge.webp": require("../../assets/images/workout/Bodyweight-Glute-Bridge.webp"),
  "../../assets/images/workout/Bodyweight-Squat.webp": require("../../assets/images/workout/Bodyweight-Squat.webp"),
  "../../assets/images/workout/Burpees.webp": require("../../assets/images/workout/Burpees.webp"),
  "../../assets/images/workout/Cable-Crossover.webp": require("../../assets/images/workout/Cable-Crossover.webp"),
  "../../assets/images/workout/Cable-One-Arm-Lateral-Raise.webp": require("../../assets/images/workout/Cable-One-Arm-Lateral-Raise.webp"),
  "../../assets/images/workout/Cable-Rope-Pushdown.webp": require("../../assets/images/workout/Cable-Rope-Pushdown.webp"),
  "../../assets/images/workout/Chest-Press-Machine.webp": require("../../assets/images/workout/Chest-Press-Machine.webp"),
  "../../assets/images/workout/Close-Grip-Bench-Press.webp": require("../../assets/images/workout/Close-Grip-Bench-Press.webp"),
  "../../assets/images/workout/Close-Grip-Pulldown.webp": require("../../assets/images/workout/Close-Grip-Pulldown.webp"),
  "../../assets/images/workout/Crunch-Machine.webp": require("../../assets/images/workout/Crunch-Machine.webp"),
  "../../assets/images/workout/Crunch.webp": require("../../assets/images/workout/Crunch.webp"),
  "../../assets/images/workout/Donkey-Kicks.webp": require("../../assets/images/workout/Donkey-Kicks.webp"),
  "../../assets/images/workout/Duck-Walk.webp": require("../../assets/images/workout/Duck-Walk.webp"),
  "../../assets/images/workout/Dumbbell-Bench-Press.webp": require("../../assets/images/workout/Dumbbell-Bench-Press.webp"),
  "../../assets/images/workout/Dumbbell-Bent-Over-Row-Single-Arm.webp": require(
    "../../assets/images/workout/Dumbbell-Bent-Over-Row-_Single-Arm.webp"
  ),
  "../../assets/images/workout/Dumbbell-Bent-Over-Row-_Single-Arm.webp": require("../../assets/images/workout/Dumbbell-Bent-Over-Row-_Single-Arm.webp"),
  "../../assets/images/workout/Dumbbell-Bent-Over-Rows.webp": require("../../assets/images/workout/Dumbbell-Bent-Over-Rows.webp"),
  "../../assets/images/workout/Dumbbell-Concentration-Curl.webp": require("../../assets/images/workout/Dumbbell-Concentration-Curl.webp"),
  "../../assets/images/workout/Dumbbell-Deadlift.webp": require("../../assets/images/workout/Dumbbell-Deadlift.webp"),
  "../../assets/images/workout/Dumbbell-Declined-Bench-Press.webp": require("../../assets/images/workout/Dumbbell-Declined-Bench-Press.webp"),
  "../../assets/images/workout/Dumbbell-Fly.webp": require("../../assets/images/workout/Dumbbell-Fly.webp"),
  "../../assets/images/workout/Dumbbell-Front-Raise.webp": require("../../assets/images/workout/Dumbbell-Front-Raise.webp"),
  "../../assets/images/workout/Dumbbell-Goblet-Squat.webp": require("../../assets/images/workout/Dumbbell-Goblet-Squat.webp"),
  "../../assets/images/workout/Dumbbell-Lateral-Raise.webp": require("../../assets/images/workout/Dumbbell-Lateral-Raise.webp"),
  "../../assets/images/workout/Dumbbell-Overhead-Triceps-Extension.webp": require("../../assets/images/workout/Dumbbell-Overhead-Triceps-Extension.webp"),
  "../../assets/images/workout/Dumbbell-Pullover.webp": require("../../assets/images/workout/Dumbbell-Pullover.webp"),
  "../../assets/images/workout/Dumbbell-Push-Press.webp": require("../../assets/images/workout/Dumbbell-Push-Press.webp"),
  "../../assets/images/workout/Dumbbell-Romanian-Deadlift.webp": require("../../assets/images/workout/Dumbbell-Romanian-Deadlift.webp"),
  "../../assets/images/workout/Dumbbell-Shoulder-Press.webp": require("../../assets/images/workout/Dumbbell-Shoulder-Press.webp"),
  "../../assets/images/workout/Dumbbell-Shrugs.webp": require("../../assets/images/workout/Dumbbell-Shrugs.webp"),
  "../../assets/images/workout/Dumbbell-Step-Up.webp": require("../../assets/images/workout/Dumbbell-Step-Up.webp"),
  "../../assets/images/workout/EZ-Barbell-Curl.webp": require("../../assets/images/workout/EZ-Barbell-Curl.webp"),
  "../../assets/images/workout/EZ-Barbell-Preacher-Curl.webp": require("../../assets/images/workout/EZ-Barbell-Preacher-Curl.webp"),
  "../../assets/images/workout/Fire-Hydrant.webp": require("../../assets/images/workout/Fire-Hydrant.webp"),
  "../../assets/images/workout/Front-Squat.webp": require("../../assets/images/workout/Front-Squat.webp"),
  "../../assets/images/workout/Glute-Ham-Raise.webp": require("../../assets/images/workout/Glute-Ham-Raise.webp"),
  "../../assets/images/workout/Good-Morning.webp": require("../../assets/images/workout/Good-Morning.webp"),
  "../../assets/images/workout/Groiners.webp": require("../../assets/images/workout/Groiners.webp"),
  "../../assets/images/workout/Hack-Squat.webp": require("../../assets/images/workout/Hack-Squat.webp"),
  "../../assets/images/workout/Hammer-Curl.webp": require("../../assets/images/workout/Hammer-Curl.webp"),
  "../../assets/images/workout/Hanging-Leg-Raise.webp": require("../../assets/images/workout/Hanging-Leg-Raise.webp"),
  "../../assets/images/workout/High-Cable-Rear-Delt-Fly.webp": require("../../assets/images/workout/High-Cable-Rear-Delt-Fly.webp"),
  "../../assets/images/workout/Incline-Barbell-Bench-Press.webp": require("../../assets/images/workout/Incline-Barbell-Bench-Press.webp"),
  "../../assets/images/workout/Incline-Dumbbell-Bench-Press.webp": require("../../assets/images/workout/Incline-Dumbbell-Bench-Press.webp"),
  "../../assets/images/workout/Incline-Dumbbell-Curl.webp": require("../../assets/images/workout/Incline-Dumbbell-Curl.webp"),
  "../../assets/images/workout/Incline-Dumbbell-Fly.webp": require("../../assets/images/workout/Incline-Dumbbell-Fly.webp"),
  "../../assets/images/workout/Jump-Squat.webp": require("../../assets/images/workout/Jump-Squat.webp"),
  "../../assets/images/workout/Kettlebell-Sumo-Deadlift.webp": require("../../assets/images/workout/Kettlebell-Sumo-Deadlift.webp"),
  "../../assets/images/workout/Kettlebell-Swing.webp": require("../../assets/images/workout/Kettlebell-Swing.webp"),
  "../../assets/images/workout/Kickback.webp": require("../../assets/images/workout/Kickback.webp"),
  "../../assets/images/workout/Knee-Tuck-Jumps.webp": require("../../assets/images/workout/Knee-Tuck-Jumps.webp"),
  "../../assets/images/workout/Leg-Extension.webp": require("../../assets/images/workout/Leg-Extension.webp"),
  "../../assets/images/workout/Leg-Press.webp": require("../../assets/images/workout/Leg-Press.webp"),
  "../../assets/images/workout/Long-Arm-Crunch.webp": require("../../assets/images/workout/Long-Arm-Crunch.webp"),
  "../../assets/images/workout/Lunge.webp": require("../../assets/images/workout/Lunge.webp"),
  "../../assets/images/workout/Lying-Dumbbell-Triceps-Extension.webp": require("../../assets/images/workout/Lying-Dumbbell-Triceps-Extension.webp"),
  "../../assets/images/workout/Lying-Leg-Curl.webp": require("../../assets/images/workout/Lying-Leg-Curl.webp"),
  "../../assets/images/workout/Lying-Triceps-Extension.webp": require("../../assets/images/workout/Lying-Triceps-Extension.webp"),
  "../../assets/images/workout/Medicine-Ball-Deadlift.webp": require("../../assets/images/workout/Medicine-Ball-Deadlift.webp"),
  "../../assets/images/workout/Medicine-Ball-Squat.webp": require("../../assets/images/workout/Medicine-Ball-Squat.webp"),
  "../../assets/images/workout/Mini-Band-Air-Squat.webp": require("../../assets/images/workout/Mini-Band-Air-Squat.webp"),
  "../../assets/images/workout/Mini-Band-Lateral-Walks.webp": require("../../assets/images/workout/Mini-Band-Lateral-Walks.webp"),
  "../../assets/images/workout/Oblique-Crunch.webp": require("../../assets/images/workout/Oblique-Crunch.webp"),
  "../../assets/images/workout/One-Arm-Low-Pulley-Front-Raise-Neutral-Grip.webp": require("../../assets/images/workout/One-Arm-Low-Pulley-Front-Raise-Neutral-Grip.webp"),
  "../../assets/images/workout/Parallel-Dip-Bar.webp": require("../../assets/images/workout/Parallel-Dip-Bar.webp"),
  "../../assets/images/workout/Peck-Deck.webp": require("../../assets/images/workout/Peck-Deck.webp"),
  "../../assets/images/workout/plank-get-ups.svg": require("../../assets/images/workout/plank-get-ups.svg"),
  "../../assets/images/workout/Plank.webp": require("../../assets/images/workout/Plank.webp"),
  "../../assets/images/workout/Plank-Get-Ups.webp": require(
    "../../assets/images/workout/plank-get-ups.svg"
  ),
  "../../assets/images/workout/Pull-Up-with-a-Supinated-Grip.webp": require("../../assets/images/workout/Pull-Up-with-a-Supinated-Grip.webp"),
  "../../assets/images/workout/Pull-Up.webp": require("../../assets/images/workout/Pull-Up.webp"),
  "../../assets/images/workout/Push-Ups.webp": require("../../assets/images/workout/Push-Ups.webp"),
  "../../assets/images/workout/Reverse-Barbell-Curl.webp": require("../../assets/images/workout/Reverse-Barbell-Curl.webp"),
  "../../assets/images/workout/Reverse-Grip-Cable-Triceps-Extension-with-Barbell.webp": require("../../assets/images/workout/Reverse-Grip-Cable-Triceps-Extension-with-Barbell.webp"),
  "../../assets/images/workout/Reverse-Grip-Pulldown.webp": require("../../assets/images/workout/Reverse-Grip-Pulldown.webp"),
  "../../assets/images/workout/Rope-Ab-Pulldown.webp": require("../../assets/images/workout/Rope-Ab-Pulldown.webp"),
  "../../assets/images/workout/Rope-Cable-Curl.webp": require("../../assets/images/workout/Rope-Cable-Curl.webp"),
  "../../assets/images/workout/Rope-Pulldown.webp": require("../../assets/images/workout/Rope-Pulldown.webp"),
  "../../assets/images/workout/Seated-Barbell-French-Press.webp": require("../../assets/images/workout/Seated-Barbell-French-Press.webp"),
  "../../assets/images/workout/Seated-Barbell-Shoulder-Press.webp": require("../../assets/images/workout/Seated-Barbell-Shoulder-Press.webp"),
  "../../assets/images/workout/Seated-Barbell-Wrist-Curl.webp": require("../../assets/images/workout/Seated-Barbell-Wrist-Curl.webp"),
  "../../assets/images/workout/Seated-Barbell-Wrist-Extension.webp": require("../../assets/images/workout/Seated-Barbell-Wrist-Extension.webp"),
  "../../assets/images/workout/Seated-Behind-the-Neck-Barbell-Shoulder-Press.webp": require("../../assets/images/workout/Seated-Behind-the-Neck-Barbell-Shoulder-Press.webp"),
  "../../assets/images/workout/Seated-Cable-Row.webp": require("../../assets/images/workout/Seated-Cable-Row.webp"),
  "../../assets/images/workout/Seated-Calf-Raise.webp": require("../../assets/images/workout/Seated-Calf-Raise.webp"),
  "../../assets/images/workout/Seated-Hip-Abduction-Machine.webp": require("../../assets/images/workout/Seated-Hip-Abduction-Machine.webp"),
  "../../assets/images/workout/Seated-Leg-Curl.webp": require("../../assets/images/workout/Seated-Leg-Curl.webp"),
  "../../assets/images/workout/Side-Lying-Hip-Raise.webp": require("../../assets/images/workout/Side-Lying-Hip-Raise.webp"),
  "../../assets/images/workout/Side-Lying-Leg-Raise.webp": require("../../assets/images/workout/Side-Lying-Leg-Raise.webp"),
  "../../assets/images/workout/Single-Arm-Cable-Front-Raise.webp": require("../../assets/images/workout/Single-Arm-Cable-Front-Raise.webp"),
  "../../assets/images/workout/Single-Arm-Cable-Triceps-Extension-with-Supinated-Grip.webp": require("../../assets/images/workout/Single-Arm-Cable-Triceps-Extension-with-Supinated-Grip.webp"),
  "../../assets/images/workout/Single-Arm-Cable-Triceps-Extension.webp": require("../../assets/images/workout/Single-Arm-Cable-Triceps-Extension.webp"),
  "../../assets/images/workout/Single-Arm-Low-Pulley-Cable-Curl.webp": require("../../assets/images/workout/Single-Arm-Low-Pulley-Cable-Curl.webp"),
  "../../assets/images/workout/Single-Leg-Bodyweight-Deadlift.webp": require("../../assets/images/workout/Single-Leg-Bodyweight-Deadlift.webp"),
  "../../assets/images/workout/Single-Leg-Extension.webp": require("../../assets/images/workout/Single-Leg-Extension.webp"),
  "../../assets/images/workout/Single-Leg-Glute-Bridge.webp": require("../../assets/images/workout/Single-Leg-Glute-Bridge.webp"),
  "../../assets/images/workout/Smith-Machine-Frog-Pump.webp": require("../../assets/images/workout/Smith-Machine-Frog-Pump.webp"),
  "../../assets/images/workout/Smith-Machine-Hip-Thrust.webp": require("../../assets/images/workout/Smith-Machine-Hip-Thrust.webp"),
  "../../assets/images/workout/Smith-Machine-Shoulder-Press.webp": require("../../assets/images/workout/Smith-Machine-Shoulder-Press.webp"),
  "../../assets/images/workout/Squat-Sit-to-Reach.webp": require("../../assets/images/workout/Squat-Sit-to-Reach.webp"),
  "../../assets/images/workout/Squat.webp": require("../../assets/images/workout/Squat.webp"),
  "../../assets/images/workout/Standing-Behind-the-Neck-Barbell-Shoulder-Press.webp": require("../../assets/images/workout/Standing-Behind-the-Neck-Barbell-Shoulder-Press.webp"),
  "../../assets/images/workout/Standing-Cable-Abduction.webp": require("../../assets/images/workout/Standing-Cable-Abduction.webp"),
  "../../assets/images/workout/Standing-Cable-Kickback.webp": require("../../assets/images/workout/Standing-Cable-Kickback.webp"),
  "../../assets/images/workout/Standing-Calf-Raise.webp": require("../../assets/images/workout/Standing-Calf-Raise.webp"),
  "../../assets/images/workout/Standing-High-Pulley-Cable-Curl.webp": require("../../assets/images/workout/Standing-High-Pulley-Cable-Curl.webp"),
  "../../assets/images/workout/Standing-Knee-Raise.webp": require("../../assets/images/workout/Standing-Knee-Raise.webp"),
  "../../assets/images/workout/Straight-Arm-Lat-Pulldown.webp": require("../../assets/images/workout/Straight-Arm-Lat-Pulldown.webp"),
  "../../assets/images/workout/Straight-Bar-Low-Pulley-Cable-Curl.webp": require("../../assets/images/workout/Straight-Bar-Low-Pulley-Cable-Curl.webp"),
  "../../assets/images/workout/T-Bar-Rows.webp": require("../../assets/images/workout/T-Bar-Rows.webp"),
  "../../assets/images/workout/Trap-Bar-Deadlift.webp": require("../../assets/images/workout/Trap-Bar-Deadlift.webp"),
  "../../assets/images/workout/Triceps-Pressdown.webp": require("../../assets/images/workout/Triceps-Pressdown.webp"),
  "../../assets/images/workout/Two-Handed-Dumbbell-Front-Raise.webp": require("../../assets/images/workout/Two-Handed-Dumbbell-Front-Raise.webp"),
  "../../assets/images/workout/Wall-Sit.webp": require("../../assets/images/workout/Wall-Sit.webp"),
  "../../assets/images/workout/Wide-Grip-Pulldown.webp": require("../../assets/images/workout/Wide-Grip-Pulldown.webp"),
};

export function getExerciseImageSource(
  image: string | undefined
): ExerciseImageSource | undefined {
  if (!image) return undefined;

  const normalizedPath = image.replace(/\\/g, "/");
  const localImage = LOCAL_EXERCISE_IMAGES[normalizedPath];
  if (localImage) return localImage;

  return image.startsWith("http://") || image.startsWith("https://")
    ? { uri: image }
    : undefined;
}
