import { StyleSheet, Text, View } from "react-native";
import { Sparkles, PenTool } from "lucide-react-native";
import { useOnboardingStore } from "@/store/onboarding-store";
import { theme } from "@/lib/theme";
import { RadioCard } from "@/components/onboarding/RadioCard";

export function StepSetupType() {
  const { setupType, setField } = useOnboardingStore();

  return (
    <View>
      <Text style={styles.title1}>WORKOUT</Text>
      <Text style={styles.title2}>SETUP</Text>
      
      <Text style={styles.subtitle}>
        How would you like to build your training program? You can change this later.
      </Text>

      <View style={styles.options}>
        <RadioCard
          title="Smart Plan"
          description="Auto-generated by our AI based on your profile and goals."
          icon={Sparkles}
          selected={setupType === "smart"}
          onSelect={() => setField("setupType", "smart")}
        />
        <RadioCard
          title="Custom Plan"
          description="Build your own routines from our exercise library."
          icon={PenTool}
          selected={setupType === "custom"}
          onSelect={() => setField("setupType", "custom")}
        />
      </View>
    </View>
  );
}

const styles = StyleSheet.create({
  title1: {
    color: theme.text,
    fontSize: 32,
    fontWeight: "900",
    letterSpacing: -1,
    lineHeight: 36,
  },
  title2: {
    color: theme.neon,
    fontSize: 32,
    fontWeight: "900",
    letterSpacing: -1,
    lineHeight: 36,
    marginBottom: 16,
  },
  subtitle: {
    color: theme.muted,
    fontSize: 14,
    lineHeight: 22,
    marginBottom: 32,
  },
  options: {
    gap: 12,
  },
});
